# Generated by Django 3.1 on 2020-08-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='rules',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='sprint_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
